# Generated by Django 4.2.2 on 2023-06-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_remove_button_count_remove_button_user_button_calls_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.button')),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_calls', models.ManyToManyField(through='stats.ButtonCall', to='chat.button')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buttoncall',
            name='user_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.userstats'),
        ),
    ]
