# Generated by Django 4.2.2 on 2023-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='count',
        ),
        migrations.RemoveField(
            model_name='button',
            name='user',
        ),
        migrations.AddField(
            model_name='button',
            name='calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
